{% set name = "authzed-py" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/authzed/authzed-{{ version }}.tar.gz
  sha256: b88eb00cfb6cf41180890803b13ab51ae50b57ea924cdd99d5dad518542e7d63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - grpcio >=1.63.0,<2.0.0
    - protobuf >=5.26,<6
    - grpc-interceptor >=0.15.4,<0.16.0
    - googleapis-common-protos >=1.65.0,<2.0.0

test:
  imports:
    - authzed
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/authzed/authzed-py
  summary: Client library for SpiceDB.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
